MODEL: #MODEL field
    framework: "RecognizerGCN" #Mandatory, indicate the type of network, associate to the 'paddlevideo/modeling/framework/' .
    backbone: #Mandatory, indicate the type of backbone, associate to the 'paddlevideo/modeling/backbones/' .
        name: "CTRGCN" #Mandatory, The name of backbone.
        num_point: 17
        num_person: 2
        base_channel: 64
        graph: "ntu_rgb_d"
        graph_args:
            labeling_mode: "spatial"
        in_channels: 3
        adaptive: True
    head:
        name: "CTRGCNHead" #Mandatory, indicate the type of head, associate to the 'paddlevideo/modeling/heads'
        num_classes: 5  #Optional, the number of classes to be classified.
        in_channels: 64
        drop_out: 0

DATASET: #DATASET field
    batch_size: 64 #Mandatory, bacth size
    num_workers: 4 #Mandatory, the number of subprocess on each GPU.
    test_batch_size: 1
    test_num_workers: 0
    train:
        format: "SkeletonDataset" #Mandatory, indicate the type of dataset, associate to the 'paddlevidel/loader/dateset'
        file_path: "/home/haoge/ymq1/test_kinetics-skeleton/train_data.npy" #Mandatory, train data index file path
        label_path: "/home/haoge/ymq1/test_kinetics-skeleton/train_label.pkl"
    valid:
        format: "SkeletonDataset" #Mandatory, indicate the type of dataset, associate to the 'paddlevidel/loader/dateset'
        file_path: "/home/haoge/ymq1/test_kinetics-skeleton/val_data.npy"  #Mandatory, valid data index file path
        label_path: "/home/haoge/ymq1/test_kinetics-skeleton/val_label.pkl"
        test_mode: True
    test:
        format: "SkeletonDataset" #Mandatory, indicate the type of dataset, associate to the 'paddlevidel/loader/dateset'
        file_path: "/home/haoge/ymq1/test_kinetics-skeleton/test_data.npy" #Mandatory, valid data index file path
        label_path: "/home/haoge/ymq1/test_kinetics-skeleton/test_label.pkl"
        test_mode: True

PIPELINE: #PIPELINE field
    train: #Mandotary, indicate the pipeline to deal with the training data, associate to the 'paddlevideo/loader/pipelines/'
        sample:
            - Iden:
            - SketeonCropSample:
                window_size: 300
                # p_interval: [0.5, 1]
                p_interval: [0.75, 1]
        transform: #Mandotary, image transfrom operator
            - RandomRotation:
                argument: True
            - SketeonModalityTransform:
                joint: False
                bone: True
                motion: True
                graph: 'ntu_rgb_d'
    valid: #Mandotary, indicate the pipeline to deal with the training data, associate to the 'paddlevideo/loader/pipelines/'
        sample:
            - Iden:
            - SketeonCropSample:
                window_size: 300
                p_interval: [0.95]
        transform: #Mandotary, image transfrom operator
            - RandomRotation:
                argument: False
            - SketeonModalityTransform:
                joint: False
                bone: True
                motion: True
                graph: 'ntu_rgb_d'
    test: #Mandotary, indicate the pipeline to deal with the training data, associate to the 'paddlevideo/loader/pipelines/'
        sample:
            - Iden:
            - SketeonCropSample:
                window_size: 300
                p_interval: [0.95]
        transform: #Mandotary, image transfrom operator
            - RandomRotation:
                argument: False
            - SketeonModalityTransform:
                joint: False
                bone: True
                motion: True
                graph: 'ntu_rgb_d'

OPTIMIZER: #OPTIMIZER field
  name: 'Momentum'
  momentum: 0.9
  learning_rate:
    name: 'CustomWarmupAdjustDecay'
    iter_step: True
    step_base_lr: 0.1
    warmup_epochs: 5
    lr_decay_rate: 0.1
    boundaries: [35, 55]
  weight_decay:
    name: 'L2'
    value: 1e-4
  use_nesterov: True


METRIC:
    name: 'SkeletonMetric'

INFERENCE:
    name: 'CTRGCN_Inference_helper'
    window_size: 300
    p_interval: [0.95]
    num_channels: 3
    vertex_nums: 17
    person_nums: 2

model_name: "test_CTRGCN_bone_motion"
log_interval: 100 #Optional, the interal of logger, default:10
epochs: 1000 #Mandatory, total epoch
save_interval: 10
