MODEL: #MODEL field
  framework: "RecognizerGCN" #Mandatory, indicate the type of network, associate to the 'paddlevideo/modeling/framework/' .
  backbone: #Mandatory, indicate the type of backbone, associate to the 'paddlevideo/modeling/backbones/' .
    name: "AGCN2s" #Mandatory, The name of backbone.
    num_point: 17
    num_person: 1
    graph: "ntu_rgb_d"
    graph_args:
      labeling_mode: "spatial"
    in_channels: 3
  head:
    name: "AGCN2sHead" #Mandatory, indicate the type of head, associate to the 'paddlevideo/modeling/heads'
    num_classes: 5  #Optional, the number of classes to be classified.
    in_channels: 64  #output the number of classes.
    M: 1  #number of people.

DATASET: #DATASET field
  batch_size: 64 #Mandatory, bacth size
  num_workers: 4 #Mandatory, the number of subprocess on each GPU.
  test_batch_size: 1
  test_num_workers: 1
  train:
    format: "SkeletonDataset" #Mandatory, indicate the type of dataset, associate to the 'paddlevidel/loader/dateset'
    file_path: "/home/haoge/2s-AGCN/data/kinetics/train_data_joint.npy" #Mandatory, train data index file path
    label_path: "/home/haoge/2s-AGCN/data/kinetics/train_label.pkl"
  valid:
    format: "SkeletonDataset" #Mandatory, indicate the type of dataset, associate to the 'paddlevidel/loader/dateset'
    file_path: "/home/haoge/2s-AGCN/data/kinetics/val_data_joint.npy" #Mandatory, train data index file path
    label_path: "/home/haoge/2s-AGCN/data/kinetics/val_label.pkl"
    test_mode: True
  test:
    format: "SkeletonDataset" #Mandatory, indicate the type of dataset, associate to the 'paddlevidel/loader/dateset'
    file_path: "/home/haoge/2s-AGCN/data/kinetics/test_data_joint.npy" #Mandatory, train data index file path
    # label_path: "/home/haoge/2s-AGCN/data/kinetics/test_label.pkl"
    test_mode: True

PIPELINE: #PIPELINE field
  train: #Mandotary, indicate the pipeline to deal with the training data, associate to the 'paddlevideo/loader/pipelines/'
    sample:
      - Iden:
    transform: #Mandotary, image transfrom operator
      - SketeonModalityTransform:
          joint: False
          bone: True
          motion: False
          graph: 'ntu_rgb_d'
  valid: #Mandotary, indicate the pipeline to deal with the training data, associate to the 'paddlevideo/loader/pipelines/'
    sample:
      - Iden:
    transform: #Mandotary, image transfrom operator
      - SketeonModalityTransform:
          joint: False
          bone: True
          motion: False
          graph: 'ntu_rgb_d'
  test: #Mandotary, indicate the pipeline to deal with the training data, associate to the 'paddlevideo/loader/pipelines/'
    sample:
      - Iden:
    transform: #Mandotary, image transfrom operator
      - SketeonModalityTransform:
          joint: False
          bone: True
          motion: False
          graph: 'ntu_rgb_d'

OPTIMIZER: #OPTIMIZER field
  name: 'Momentum'
  momentum: 0.9
  learning_rate:
    iter_step: True
    name: 'CustomWarmupAdjustDecay'
    step_base_lr: 0.1
    warmup_epochs: 5
    lr_decay_rate: 0.1
    boundaries: [ 30, 40 ]
  weight_decay:
    name: 'L2'
    value: 1e-4
  use_nesterov: True


METRIC:
  name: 'SkeletonMetric'
  out_file: 'submission_2sgcn_bone_best_pipl.csv'

INFERENCE:
  name: 'AGCN2s_Inference_helper'
  num_channels: 3
  vertex_nums: 17
  person_nums: 1
  window_size: 150

model_name: "AGCN2s_cs_bone"
log_interval: 10 #Optional, the interal of logger, default:10
epochs: 1000 #Mandatory, total epoch
save_interval: 10
