MODEL: #MODEL field
   framework: "RecognizerGCN" #Mandatory, indicate the type of network, associate to the 'paddlevideo/modeling/framework/' .
   backbone: #Mandatory, indicate the type of backbone, associate to the 'paddlevideo/modeling/backbones/' .
       name: "AGCN" #Mandatory, The name of backbone.
   head:
       name: "STGCNHead" #Mandatory, indicate the type of head, associate to the 'paddlevideo/modeling/heads'
       num_classes: 5  #Optional, the number of classes to be classified.
       ls_eps: 0.1   #label_smooth

DATASET: #DATASET field
  batch_size: 64 #Mandatory, bacth size
  num_workers: 4 #Mandatory, the number of subprocess on each GPU.
  test_batch_size: 1
  test_num_workers: 0
  train:
       format: "SkeletonDataset" #Mandatory, indicate the type of dataset, associate to the 'paddlevidel/loader/dateset'
       file_path: "/home/haoge/ymq1/nosize_kinetics-skeleton/train_data.npy" #Mandatory, train data index file path
       label_path: "/home/haoge/ymq1/nosize_kinetics-skeleton/train_label.pkl"
  test:
       format: "SkeletonDataset" #Mandatory, indicate the type of dataset, associate to the 'paddlevidel/loader/dateset'
       file_path: "/home/haoge/ymq1/nosize_kinetics-skeleton/test_data.npy" #Mandatory, valid data index file path
       label_path: "/home/haoge/ymq1/nosize_kinetics-skeleton/test_label.pkl"
       test_mode: True
  valid: #我自己加的
       format: "SkeletonDataset" #Mandatory, indicate the type of dataset, associate to the 'paddlevidel/loader/dateset'
       file_path: "/home/haoge/ymq1/nosize_kinetics-skeleton/val_data.npy"  #Mandatory, valid data index file path
       label_path: "/home/haoge/ymq1/nosize_kinetics-skeleton/val_label.pkl"
       test_mode: True

PIPELINE: #PIPELINE field
  train: #Mandotary, indicate the pipeline to deal with the training data, associate to the 'paddlevideo/loader/pipelines/'
       sample:
           name: "AutoPadding"
           window_size: 300
       transform: #Mandotary, image transfrom operator
           - SkeletonNorm:
  test: #Mandatory, indicate the pipeline to deal with the validing data. associate to the 'paddlevideo/loader/pipelines/'
       sample:
           name: "AutoPadding"
           window_size: 300
       transform: #Mandotary, image transfrom operator
           - SkeletonNorm:
  valid: #Mandatory, indicate the pipeline to deal with the validing data. associate to the 'paddlevideo/loader/pipelines/'
       sample:
           name: "AutoPadding"
           window_size: 300
       transform: #Mandotary, image transfrom operator
           - SkeletonNorm:

OPTIMIZER: #OPTIMIZER field
 name: 'Momentum'
 momentum: 0.9
 learning_rate:
   iter_step: True
   name: 'CustomWarmupCosineDecay'
   max_epoch: 100
   warmup_epochs: 10
   warmup_start_lr: 0.005
   cosine_base_lr: 0.05
 weight_decay:
   name: 'L2'
   value: 1e-4

MIX:
   name: "Mixup"
   alpha: 0.2


METRIC:
   name: 'SkeletonMetric'
   out_file: 'submission_agcn.csv'


INFERENCE:
   name: 'STGCN_Inference_helper'
   num_channels: 2
   window_size: 300
   vertex_nums: 17
   person_nums: 2


model_name: "nosize_AGCN"
log_interval: 10 #Optional, the interal of logger, default:10
epochs: 1000 #Mandatory, total epoch
validate: True
